// This big JSON object contains configurable variables, and list of elements for the system to use during generation.

registry = {
  "namespace": "infinonaut",
  "numDimensions": 10,
  "numBiomes": [2, 5, 3, 0.75],
  "biome": {
    "depth": [-2, 3, 0.5, 0.9, 3],
    "scale": [0, 3, 0.025, 0.7, 3],
  },
  "mobs": {
    "peaceful": [
      //"minecraft:ash",
      "minecraft:bat",
      "minecraft:cat",
      "minecraft:cave_spider",
      "minecraft:chicken",
      "minecraft:cow",
      "minecraft:donkey",
      "minecraft:fox",
      "minecraft:goat",
      "minecraft:horse",
      "minecraft:husk",
      "minecraft:llama",
      "minecraft:mooshroom",
      "minecraft:panda",
      "minecraft:parrot",
      "minecraft:pig",
      "minecraft:polar_bear",
      "minecraft:rabbit",
      "minecraft:sheep",
      "minecraft:turtle",
      //"minecraft:white_ash",
      "minecraft:wolf",
    ],
    "water": [
      "minecraft:axolotl",
      "minecraft:cod",
      "minecraft:dolphin",
      "minecraft:pufferfish",
      "minecraft:squid",
      "minecraft:glow_squid",
      "minecraft:ocelot",
      "minecraft:salmon",
      "minecraft:tropical_fish",
    ],
    "harmful": [
      "minecraft:drowned",
      "minecraft:enderman",
      //"minecraft:hoglin",
      "minecraft:skeleton",
      "minecraft:slime",
      "minecraft:spider",
      "minecraft:stray",
      "minecraft:witch",
      //"minecraft:vex",
      "minecraft:zombie",
      "minecraft:zombie_villager",
      "minecraft:creeper",
      //"minecraft:ravager",
      //"minecraft:vindicator",
    ],
  },
  "surfaces": [
    "minecraft:badlands",
    //"minecraft:basalt_deltas",
    //"minecraft:crimson_forest",
    "minecraft:desert",
    //"minecraft:end",
    //"minecraft:eroded_badlands",
    "minecraft:frozen_ocean",
    //"minecraft:full_sand",
    //"minecraft:giant_tree_taiga",
    "minecraft:grass",
    "minecraft:gravelly_mountain",
    "minecraft:ice_spikes",
    "minecraft:mountain",
    "minecraft:mycelium",
    //"minecraft:nether",
    //"minecraft:nope",
    //"minecraft:ocean_sand",
    "minecraft:shattered_savanna",
    //"minecraft:soul_sand_valley",
    //"minecraft:stone",
    "minecraft:swamp",
    //"minecraft:warped_forest",
    "minecraft:wooded_badlands",
  ],
};
